version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - 9090:9090
    environment:
      PORT: 9090
      REDIS_URL: redis
      POSTGRES_URL: postgres

  redis:
    image: redis:alpine

  postgres:
    build:
      context: .
      dockerfile: postgres.Dockerfile
