version: "3.3"

services:
  web:
    build: .
    ports:
      - 9090:9090
    environment:
      PORT: 9090
      REDIS_URL: redis:6379

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
